#cloud-config
users:
 - name: root
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHgAWJRB1phor3yFZd/GZBaVIZUzYc8KyrpSzQnEH7lJ user@worknout

timezone: Europe/Moscow
#package_update: true
#package_upgrade: true
#repo_update: true
#repo_upgrade: true

#apt:
#  preserve_sources_list: true
#packages:
#  - memcached
#runcmd:
#  - [ systemctl, enable, memcached.service ]
#  - [ systemctl, start, memcached.service ]
#  - [ systemctl, nginx-reload ]
#  - [ systemctl, start, --no-block, nginx.service ]
#  - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) > /var/www/html/index.html" ]
  